.TH std::list<T,Allocator>::get_allocator 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::list<T,Allocator>::get_allocator \- std::list<T,Allocator>::get_allocator

.SH Synopsis
   allocator_type get_allocator() const;

   Returns the allocator associated with the container.

.SH Parameters

   \fI(none)\fP

.SH Return value

   The associated allocator.

.SH Complexity

   Constant.
