.TH std::mersenne_twister_engine<UIntType,w,n,m,r,a,u,d,s,b,t,c,l,f>::operator() 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::mersenne_twister_engine<UIntType,w,n,m,r,a,u,d,s,b,t,c,l,f>::operator() \- std::mersenne_twister_engine<UIntType,w,n,m,r,a,u,d,s,b,t,c,l,f>::operator()

.SH Synopsis

  result_type operator()();  \fI(since C++11)\fP

  Generates a pseudo-random value. The state of the engine is advanced by one position.

   This section is incomplete


.SH Parameters

  \fI(none)\fP

.SH Return value

  A pseudo-random number in [min(), max()].

.SH Complexity

  Amortized constant.

.SH See also


          advances the engine's state by a specified amount
  discard \fI(public member function)\fP




