.TH std::vector<T,Allocator>::capacity 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::vector<T,Allocator>::capacity \- std::vector<T,Allocator>::capacity

.SH Synopsis

size_type capacity() const;           \fI(until C++11)\fP
size_type capacity() const noexcept;  \fI(since C++11)\fP

Returns the number of elements that the container has currently allocated space for.

.SH Parameters

\fI(none)\fP

.SH Return value

Capacity of the currently allocated storage.

.SH Complexity

Constant.

.SH See also


        returns the number of elements
size    \fI(public member function)\fP
        reserves storage
reserve \fI(public member function)\fP




