.TH std::unordered_map<Key,T,Hash,KeyEqual,Allocator>::max_bucket_count 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_map<Key,T,Hash,KeyEqual,Allocator>::max_bucket_count \- std::unordered_map<Key,T,Hash,KeyEqual,Allocator>::max_bucket_count

.SH Synopsis

  size_type max_bucket_count() const;  \fI(since C++11)\fP

  Returns the maximum number of buckets the container is able to hold due to system or library implementation limitations.

.SH Parameters

  \fI(none)\fP

.SH Return value

  Maximum number of buckets.

.SH Complexity

  Constant.

.SH See also


               returns the number of buckets
  bucket_count \fI(public member function)\fP




