.TH std::unordered_map<Key,T,Hash,KeyEqual,Allocator>::load_factor 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_map<Key,T,Hash,KeyEqual,Allocator>::load_factor \- std::unordered_map<Key,T,Hash,KeyEqual,Allocator>::load_factor

.SH Synopsis

  float load_factor() const;  \fI(since C++11)\fP

  Returns the average number of elements per bucket, that is, size() divided by bucket_count().

.SH Parameters

  \fI(none)\fP

.SH Return value

  Average number of elements per bucket.

.SH Complexity

  Constant.

.SH See also


                  manages maximum average number of elements per bucket
  max_load_factor \fI(public member function)\fP




