.TH std::chrono::month_day_last 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month_day_last \- std::chrono::month_day_last

.SH Synopsis

Defined in header <chrono>
class month_day_last;       \fI(since C++20)\fP

The class month_day_last represents the last day of a specific month, of some yet to be specified year.
month_day_last is a TriviallyCopyable StandardLayoutType.

.SH Member functions


              constructs a month_day_last
constructor   \fI(public member function)\fP
              accesses the stored month
month         \fI(public member function)\fP
              checks if the stored month is valid
ok            \fI(public member function)\fP


Nonmember functions



operator==
operator!= compares two month_day_last objects
operator<  \fI(function)\fP
operator<=
operator>
operator>=
           outputs a month_day_last into a stream
operator<< \fI(function template)\fP




