.TH std::putwchar 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::putwchar \- std::putwchar

.SH Synopsis

Defined in header <cwchar>
wint_t putwchar( wchar_t ch );

Writes a wide character ch to stdout

.SH Parameters


ch - wide character to be written


.SH Return value

ch on success, WEOF on failure.

.SH See also


        writes a character to stdout
putchar \fI(function)\fP
        writes a wide character to a file stream
fputwc  \fI(function)\fP
putwc




