.TH std::chrono::weekday_indexed 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::weekday_indexed \- std::chrono::weekday_indexed

.SH Synopsis

Defined in header <chrono>
class weekday_indexed;      \fI(since C++20)\fP

The class weekday_indexed combines a weekday, representing a day of the week in the Gregorian calendar, with a small index n in the range [1, 5]. It represents the first, second, third, fourth, or fifth weekday of some month.
weekday_indexed is a TriviallyCopyable StandardLayoutType.

.SH Member functions


              constructs a weekday_indexed
constructor   \fI(public member function)\fP
              access the stored weekday
weekday       \fI(public member function)\fP
              access the stored index
index         \fI(public member function)\fP
              checks if the weekday and index are both valid
ok            \fI(public member function)\fP


Nonmember functions


           compares two weekday_indexed objects
operator== \fI(function)\fP
operator!=
           outputs a weekday_indexed into a stream
operator<< \fI(function template)\fP




