.TH std::queue<T,Container>::empty 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::queue<T,Container>::empty \- std::queue<T,Container>::empty

.SH Synopsis

bool empty() const;                \fI(until C++20)\fP
[[nodiscard]] bool empty() const;  \fI(since C++20)\fP

Checks if the underlying container has no elements, i.e. whether c.empty().

.SH Parameters

\fI(none)\fP

.SH Return value

true if the underlying container is empty, false otherwise

.SH Complexity

Constant

.SH See also


     returns the number of elements
size \fI(public member function)\fP




