.TH std::subtract_with_carry_engine<UIntType,w,s,r>::operator() 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::subtract_with_carry_engine<UIntType,w,s,r>::operator() \- std::subtract_with_carry_engine<UIntType,w,s,r>::operator()

.SH Synopsis

result_type operator()();  \fI(since C++11)\fP

Generates a pseudo-random value. The state of the engine is advanced by one position.

 This section is incomplete


.SH Parameters

\fI(none)\fP

.SH Return value

A pseudo-random number in [min(), max()].

.SH Complexity

Amortized constant.

.SH See also


        advances the engine's state by a specified amount
discard \fI(public member function)\fP




