.TH std::basic_string_view<CharT,Traits>::max_size 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_string_view<CharT,Traits>::max_size \- std::basic_string_view<CharT,Traits>::max_size

.SH Synopsis

  constexpr size_type max_size() const noexcept;  \fI(since C++17)\fP

  The largest possible number of char-like objects that can be referred to by a basic_string_view.

.SH Parameters

  \fI(none)\fP

.SH Return value

  Maximum number of characters.

.SH Complexity

  Constant.

.SH See also


         returns the number of characters
  size   \fI(public member function)\fP
  length
         checks whether the view is empty
  empty  \fI(public member function)\fP




