.TH std::experimental::get_underlying 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::get_underlying \- std::experimental::get_underlying

.SH Synopsis

template< class T >                                                        (library fundamentals TS v2)
constexpr T& get_underlying(propagate_const<T>& pt) noexcept;
template< class T >                                                        (library fundamentals TS v2)
constexpr const T& get_underlying(const propagate_const<T>& pt) noexcept;

Retrieves a reference to the pointer-like object stored in a propagate_const.

.SH Parameters


pt - a propagate_const object


.SH Return value

A reference to the pointer-like object stored in pt.



