.TH std::unordered_set<Key,Hash,KeyEqual,Allocator>::hash_function 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_set<Key,Hash,KeyEqual,Allocator>::hash_function \- std::unordered_set<Key,Hash,KeyEqual,Allocator>::hash_function

.SH Synopsis

hasher hash_function() const;  \fI(since C++11)\fP

Returns the function that hashes the keys.

.SH Parameters

\fI(none)\fP

.SH Return value

The hash function.

.SH Complexity

Constant.

.SH See also


       returns the function used to compare keys for equality
key_eq \fI(public member function)\fP




