.TH std::span<T,Extent>::data 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::span<T,Extent>::data \- std::span<T,Extent>::data

.SH Synopsis

constexpr pointer data() const noexcept;

Returns a pointer to the beginning of the sequence.

.SH Return value

A pointer to the beginning of the sequence.

.SH See also


              constructs a span
constructor   \fI(public member function)\fP




