.TH std::experimental::pmr::memory_resource 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::pmr::memory_resource \- std::experimental::pmr::memory_resource

.SH Synopsis

Defined in header <experimental/memory_resource>
class memory_resource;                            (library fundamentals TS)

The class std::experimental::pmr::memory_resource is an abstract interface to an unbounded set of classes encapsulating memory resources.

.SH Member functions



constructor           constructs a new memory_resource
                      \fI(public member function)\fP
(implicitly declared)

destructor            destructs an memory_resource
                      \fI(virtual public member function)\fP
\fB[virtual]\fP

operator=             Implicitly declared copy assignment operator
                      \fI(public member function)\fP
(implicitly declared)

.SH Public member functions

                      allocates memory
allocate              \fI(public member function)\fP
                      deallocates memory
deallocate            \fI(public member function)\fP
                      compare for equality with another memory_resource
is_equal              \fI(public member function)\fP

.SH Protected member functions


do_allocate           allocates memory
                      \fI(virtual protected member function)\fP
\fB[virtual]\fP

do_deallocate         deallocates memory
                      \fI(virtual protected member function)\fP
\fB[virtual]\fP

do_is_equal           compare for equality with another memory_resource
                      \fI(virtual protected member function)\fP
\fB[virtual]\fP


Non-member-functions


           compare two memory_resources
operator== \fI(function)\fP
operator!=




