.TH std::initializer_list<T>::begin 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::initializer_list<T>::begin \- std::initializer_list<T>::begin

.SH Synopsis

  const T* begin() const noexcept;            \fI(since C++11)\fP
                                              \fI(until C++14)\fP
  constexpr const T* begin() const noexcept;  \fI(since C++14)\fP

  Returns a pointer to the first element in the initializer list.
  If the initializer list is empty, the values of begin() and end() are unspecified, but will be identical.

.SH Parameters

  \fI(none)\fP

.SH Return value

  a pointer to the first element in the initializer list

.SH Complexity

  Constant

.SH See also


      returns a pointer to one past the last element
  end \fI(public member function)\fP




