.TH std::basic_syncbuf<CharT,Traits,Allocator>::get_allocator 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::basic_syncbuf<CharT,Traits,Allocator>::get_allocator \- std::basic_syncbuf<CharT,Traits,Allocator>::get_allocator

.SH Synopsis

allocator_type get_allocator() const noexcept;

Returns a copy of the allocator that was passed in as the constructor argument or replaced through the assignment operator.

.SH Parameters

\fI(none)\fP

.SH Example


 This section is incomplete
 Reason: no example


.SH See also


              constructs a basic_syncbuf object
constructor   \fI(public member function)\fP
              assigns a basic_syncbuf object
operator=     \fI(public member function)\fP




