.TH std::destroying_delete_t,std::destroying_delete 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::destroying_delete_t,std::destroying_delete \- std::destroying_delete_t,std::destroying_delete

.SH Synopsis

Defined in header <new>
struct destroying_delete_t { explicit destroying_delete_t() = default; };  \fI(since C++20)\fP
inline constexpr destroying_delete_t destroying_delete{};                  \fI(since C++20)\fP

Tag type used to identify the destroying delete form of operator_delete.

.SH See also


                  deallocation functions
operator_delete   \fI(function)\fP
operator_delete[]




