.TH std::is_execution_policy 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::is_execution_policy \- std::is_execution_policy

.SH Synopsis

Defined in header <execution>
template< class T >            \fI(since C++17)\fP
struct is_execution_policy;

Checks whether T is a standard or implementation-defined execution policy type.
Provides the member constant value which is equal to true, if T is a_standard_execution_policy_type, or an implementation-defined execution policy type. Otherwise, value is equal to false.
The behavior of a program that adds specializations for std::is_execution_policy is undefined.

.SH Template parameters


T - a type to check


Helper template


Defined in header <execution>
template< class T >                                                                \fI(since C++17)\fP
inline constexpr bool is_execution_policy_v = std::is_execution_policy<T>::value;


Inherited from std::integral_constant


.SH Member constants



value    true if T is a standard or implementation-defined execution policy type, false otherwise
         \fI(public static member constant)\fP
\fB[static]\fP


.SH Member functions


              converts the object to bool, returns value
operator bool \fI(public member function)\fP

operator()    returns value
              \fI(public member function)\fP
\fI(C++14)\fP


.SH Member types


Type       Definition
value_type bool
type       std::integral_constant<bool, value>


.SH See also



sequenced_policy
parallel_policy
parallel_unsequenced_policy
unsequenced_policy          execution policy types
                            \fI(class)\fP
\fI(C++17)\fP
\fI(C++17)\fP
\fI(C++17)\fP
(C++20)

seq
par
par_unseq
unseq                       global execution policy objects
                            (constant)
\fI(C++17)\fP
\fI(C++17)\fP
\fI(C++17)\fP
(C++20)




