.TH std::gslice_array 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::gslice_array \- std::gslice_array

.SH Synopsis

Defined in header <valarray>
template< class T > class gslice_array;

std::gslice_array is a helper template used by std::gslice subscript operator. It has reference semantics to a subset of the array specified by the std::gslice object.

.SH Member types


Type       Definition
value_type T


.SH Member functions


              constructs a gslice_array
constructor   \fI(public member function)\fP
              destroys a gslice_array
destructor    \fI(public member function)\fP
              assigns contents
operator=     \fI(public member function)\fP

operator+=
operator-=
operator*=
operator/=    performs arithmetic operation on the array referred by generic slice.
operator%=    \fI(public member function)\fP
operator&=
operator|=
operator^=
operator<<=
operator>>=


.SH Example


 This section is incomplete
 Reason: no example


.SH See also


            proxy to a subset of a valarray after applying a slice
slice_array \fI(class template)\fP




