.TH std::experimental::promise<R>::get_memory_resource 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::promise<R>::get_memory_resource \- std::experimental::promise<R>::get_memory_resource

.SH Synopsis

std::experimental::pmr::memory_resource* get_memory_resource() const noexcept;  (library fundamentals TS)

Returns a pointer to the memory resource used by this object to allocate memory.

.SH Parameters

\fI(none)\fP

.SH Return value

A pointer to the memory resource used by this object to allocate memory.

.SH See also


              constructs the promise object
constructor   \fI(public member function)\fP




