.TH std::auto_ptr<T>::release 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::auto_ptr<T>::release \- std::auto_ptr<T>::release

.SH Synopsis

  T* release() throw();  (deprecated in C++11)
                         (removed in C++17)

  Releases the held pointer. After the call *this holds the null pointer.

.SH Parameters

  \fI(none)\fP

.SH Return value

  get().

.SH See also


        destroys the managed object
  reset \fI(public member function)\fP




