.TH std::clock_t 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::clock_t \- std::clock_t

.SH Synopsis

  Defined in header <ctime>
  typedef /* unspecified */ clock_t;

  Arithmetic type capable of representing the process running time of implementation-defined range and precision.

.SH See also


                 returns raw processor clock time since the program is started
  clock          \fI(function)\fP
                 number of processor clock ticks per second
  CLOCKS_PER_SEC (macro constant)




