.TH std::scoped_allocator_adaptor<OuterAlloc,InnerAlloc...>::select_on_container_copy_construction 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::scoped_allocator_adaptor<OuterAlloc,InnerAlloc...>::select_on_container_copy_construction \- std::scoped_allocator_adaptor<OuterAlloc,InnerAlloc...>::select_on_container_copy_construction

.SH Synopsis

Defined in header <scoped_allocator>
scoped_allocator_adaptor select_on_container_copy_construction() const;  \fI(since C++11)\fP

Creates a new instance of std::scoped_allocator_adaptor, where the outer allocator base class and each inner allocator subobject are obtained by calling std::allocator_traits<A>::select_on_container_copy_construction().

.SH Parameters

\fI(none)\fP

.SH Return value

A new std::scoped_allocator_adaptor object, constructed from correctly copied allocators.

.SH See also



select_on_container_copy_construction obtains the allocator to use after copying a standard container
                                      \fI(public static member function of std::allocator_traits<Alloc>)\fP
\fB[static]\fP




