.TH std::new_handler 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::new_handler \- std::new_handler

.SH Synopsis

  Defined in header <new>
  typedef void (*new_handler)();

  std::new_handler is the function pointer type (pointer to function that takes no arguments and returns void), which is used by the functions std::set_new_handler and std::get_new_handler

.SH See also


                  allocation functions
  operator_new    \fI(function)\fP
  operator_new[]
                  registers a new handler
  set_new_handler \fI(function)\fP

  get_new_handler obtains the current new handler
                  \fI(function)\fP
  \fI(C++11)\fP




