.TH std::hash(std::experimental::shared_ptr) 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::hash(std::experimental::shared_ptr) \- std::hash(std::experimental::shared_ptr)

.SH Synopsis
   template<class T> struct hash<std::experimental::shared_ptr<T>>;  (library fundamentals TS)

   The template specialization of std::hash for std::experimental::shared_ptr<T> allows users to obtain hashes of objects of type std::experimental::shared_ptr<T>.

   For a given std::experimental::shared_ptr<T> p, this specialization ensures that std::hash<std::experimental::shared_ptr<T>>()(p) == std::hash<T*>()(p.get()).

.SH Example

    This section is incomplete
    Reason: no example

.SH See also

   hash    hash function object
   \fI(C++11)\fP \fI(class template)\fP
