.TH std::exception::operator= 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::exception::operator= \- std::exception::operator=

.SH Synopsis

  exception& operator=( const exception& other ) throw();   \fI(until C++11)\fP
  exception& operator=( const exception& other ) noexcept;  \fI(since C++11)\fP

  Copy assignment operator. Assigns the contents of other

  The effects of calling what() after assignment are implementation-defined.                            \fI(until C++11)\fP
  If *this and other both have dynamic type std::exception then std::strcmp(what(), other.what()) == 0. \fI(since C++11)\fP


.SH Parameters


  other - another exception to assign the contents of




