.TH std::unordered_set<Key,Hash,KeyEqual,Allocator>::bucket_size 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unordered_set<Key,Hash,KeyEqual,Allocator>::bucket_size \- std::unordered_set<Key,Hash,KeyEqual,Allocator>::bucket_size

.SH Synopsis

  size_type bucket_size( size_type n ) const;  \fI(since C++11)\fP

  Returns the number of elements in the bucket with index n.

.SH Parameters


  n - the index of the bucket to examine


.SH Return value

  The number of elements in the bucket n.

.SH Complexity

  Linear in the size of the bucket n.

.SH See also


               returns the number of buckets
  bucket_count \fI(public member function)\fP




