.TH std::multiset<Key,Compare,Allocator>::value_comp 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::multiset<Key,Compare,Allocator>::value_comp \- std::multiset<Key,Compare,Allocator>::value_comp

.SH Synopsis

  std::multiset::value_compare value_comp() const;

  Returns the function object that compares the values. It is the same as key_comp.

.SH Parameters

  \fI(none)\fP

.SH Return value

  The value comparison function object.

.SH Complexity

  Constant.

.SH See also


           returns the function that compares keys
  key_comp \fI(public member function)\fP




