.TH std::chrono::month::operator+=,std::chrono::month::operator-= 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month::operator+=,std::chrono::month::operator-= \- std::chrono::month::operator+=,std::chrono::month::operator-=

.SH Synopsis

constexpr std::chrono::month& operator+=(const std::chrono::months& m) noexcept; \fB(1)\fP \fI(since C++20)\fP
constexpr std::chrono::month& operator+=(const std::chrono::months& m) noexcept; \fB(2)\fP \fI(since C++20)\fP

Adds or subtracts m.count() from the month value, reducing the result modulo 12 to an integer in the range [1, 12].
1) Performs *this = *this + m;
2) Performs *this = *this - m;

.SH Return value

A reference to this month after modification.

.SH Notes

After a call to one of these functions, ok() is always true if no overflow occurred during the operation.

.SH Example


 This section is incomplete
 Reason: no example


.SH See also



operator++      increments or decrements the month
operator++(int) \fI(public member function)\fP
operator--
operator--(int)
                performs arithmetic on months
operator+       \fI(function)\fP
operator-




