.TH std::error_code::value 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::error_code::value \- std::error_code::value

.SH Synopsis

  int value() const noexcept;  \fI(since C++11)\fP

  Returns the platform dependent error value.

.SH Parameters

  \fI(none)\fP

.SH Return value

  The platform-dependent error value.

.SH See also


           obtains the error_category for this error_code
  category \fI(public member function)\fP




