.TH std::list<T,Allocator>::pop_front 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::list<T,Allocator>::pop_front \- std::list<T,Allocator>::pop_front

.SH Synopsis

void pop_front();

Removes the first element of the container. If there are no elements in the container, the behavior is undefined.
References and iterators to the erased element are invalidated.

.SH Parameters

\fI(none)\fP

.SH Return value

\fI(none)\fP

.SH Complexity

Constant.

.SH Exceptions

Does not throw.

.SH See also


           removes the last element
pop_back   \fI(public member function)\fP
           inserts an element to the beginning
push_front \fI(public member function)\fP




