.TH std::experimental::latch 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::latch \- std::experimental::latch

.SH Synopsis

  Defined in header <experimental/latch>
  class latch;                            (concurrency TS)

  The latch class is a downward counter of type ptrdiff_t which can be used to synchronize threads. The value of the counter is initialized on creation. Threads may block on the latch until the counter is decremented to zero. There is no possibility to increase or reset the counter, which makes the latch a single-use barrier.
  Unlike std::experimental::barrier, std::experimental::latch can be decremented by a participating thread more than once.

.SH Member functions


                      constructs a latch
  constructor         \fI(public member function)\fP
                      destroys the latch
  destructor          \fI(public member function)\fP

  operator=           not copy-assignable
                      \fI(public member function)\fP
  [deleted]
                      decrements the counter by 1 and blocks until it reaches zero
  count_down_and_wait \fI(public member function)\fP
                      decrements the counter in a non-blocking manner
  count_down          \fI(public member function)\fP
                      tests if the internal counter equals zero
  is_ready            \fI(public member function)\fP
                      blocks until the counter reaches zero
  wait                \fI(public member function)\fP




