.TH std::queue<T,Container>::pop 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::queue<T,Container>::pop \- std::queue<T,Container>::pop

.SH Synopsis

void pop();

Removes an element from the front of the queue. Effectively calls c.pop_front()

.SH Parameters

\fI(none)\fP

.SH Return value

\fI(none)\fP

.SH Complexity

Equal to the complexity of Container::pop_front.

.SH See also



emplace constructs element in-place at the end
        \fI(public member function)\fP
\fI(C++11)\fP
        inserts element at the end
push    \fI(public member function)\fP
        access the first element
front   \fI(public member function)\fP




