.TH std::chrono::weekday_last 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::weekday_last \- std::chrono::weekday_last

.SH Synopsis

  Defined in header <chrono>
  class weekday_last;         \fI(since C++20)\fP

  The class weekday_last represents the last weekday of some month.
  weekday_last is a TriviallyCopyable StandardLayoutType.

.SH Member functions


                constructs a weekday_last object
  constructor   \fI(public member function)\fP
                accesses the stored weekday
  weekday       \fI(public member function)\fP
                checks if the stored weekday is valid
  ok            \fI(public member function)\fP


  Nonmember functions


             compares two weekday_last objects
  operator== \fI(function)\fP
  operator!=
             outputs a weekday_last into a stream
  operator<< \fI(function template)\fP




