.TH std::filesystem::recursive_directory_iterator::operator= 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::filesystem::recursive_directory_iterator::operator= \- std::filesystem::recursive_directory_iterator::operator=

.SH Synopsis

recursive_directory_iterator& operator=( const recursive_directory_iterator& other ) = default;  \fI(since C++17)\fP
recursive_directory_iterator& operator=( recursive_directory_iterator&& other ) = default;       \fI(since C++17)\fP

Assigns a recursive directory iterator.

.SH Parameters


other - another directory iterator to assign


.SH Return value

*this

.SH Exceptions

\fI(none)\fP

 This section is incomplete




