.TH std::optional<T>::reset 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::optional<T>::reset \- std::optional<T>::reset

.SH Synopsis

  void reset() noexcept;  \fI(since C++17)\fP

  If *this contains a value, destroy that value as if by value().T::~T(). Otherwise, there are no effects.
  *this does not contain a value after this call.

.SH See also


            assigns contents
  operator= \fI(public member function)\fP




