.TH std::any::~any 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::any::~any \- std::any::~any

.SH Synopsis

~any();  \fI(since C++17)\fP

Destroys the contained object, if any, as if by a call to reset().

.SH See also


      destroys contained object
reset \fI(public member function)\fP




