.TH std::chrono::weekday 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::weekday \- std::chrono::weekday

.SH Synopsis

  Defined in header <chrono>
  class weekday;                                       \fI(since C++20)\fP
  inline constexpr std::chrono::weekday Sunday{0};     \fI(since C++20)\fP
  inline constexpr std::chrono::weekday Monday{1};     \fI(since C++20)\fP
  inline constexpr std::chrono::weekday Tuesday{2};    \fI(since C++20)\fP
  inline constexpr std::chrono::weekday Wednesday{3};  \fI(since C++20)\fP
  inline constexpr std::chrono::weekday Thursday{4};   \fI(since C++20)\fP
  inline constexpr std::chrono::weekday Friday{5};     \fI(since C++20)\fP
  inline constexpr std::chrono::weekday Saturday{6};   \fI(since C++20)\fP

  The class weekday represent a day of the week in the Gregorian calendar. Its normal range is [0, 6], for Sunday through Saturday, but it can hold any value in the range [0, 255]. Seven named constants are predefined in the std::chrono namespace for the seven days of the week.
  weekday is a TriviallyCopyable StandardLayoutType.

.SH Member functions


                    constructs a weekday
  constructor       \fI(public member function)\fP

  operator++        increments or decrements the weekday
  operator++(int)   \fI(public member function)\fP
  operator--
  operator--(int)
                    adds or subtracts a number of days
  operator+=        \fI(public member function)\fP
  operator-=
                    retrieves the stored weekday value
  operator_unsigned \fI(public member function)\fP
                    checks if the stored weekday value is valid
  ok                \fI(public member function)\fP
                    convenience syntax for constructing a weekday_indexed or weekday_last from this weekday
  operator[]        \fI(public member function)\fP


  Nonmember functions


              compares two weekday objects
  operator==  \fI(function)\fP
  operator!=
              performs arithmetic on weekdays
  operator+   \fI(function)\fP
  operator-
              outputs a weekday into a stream
  operator<<  \fI(function template)\fP
              outputs a weekday into a stream according to the provided format
  to_stream   \fI(function template)\fP
              parses a weekday from a stream according to the provided format
  from_stream \fI(function template)\fP




