.TH std::chrono::month 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::month \- std::chrono::month

.SH Synopsis

  Defined in header <chrono>
  class month;                                       \fI(since C++20)\fP
  inline constexpr std::chrono::month January{1};    \fI(since C++20)\fP
  inline constexpr std::chrono::month February{2};   \fI(since C++20)\fP
  inline constexpr std::chrono::month March{3};      \fI(since C++20)\fP
  inline constexpr std::chrono::month April{4};      \fI(since C++20)\fP
  inline constexpr std::chrono::month May{5};        \fI(since C++20)\fP
  inline constexpr std::chrono::month June{6};       \fI(since C++20)\fP
  inline constexpr std::chrono::month July{7};       \fI(since C++20)\fP
  inline constexpr std::chrono::month August{8};     \fI(since C++20)\fP
  inline constexpr std::chrono::month September{9};  \fI(since C++20)\fP
  inline constexpr std::chrono::month October{10};   \fI(since C++20)\fP
  inline constexpr std::chrono::month November{11};  \fI(since C++20)\fP
  inline constexpr std::chrono::month December{12};  \fI(since C++20)\fP

  The class month represents a month in a year. Its normal range is [1, 12], but it may hold any number in [0, 255]. Twelve named constants are predefined in the std::chrono namespace for the twelve months of the year.
  month is a TriviallyCopyable StandardLayoutType.

.SH Member functions


                    constructs a month
  constructor       \fI(public member function)\fP

  operator++        increments or decrements the month
  operator++(int)   \fI(public member function)\fP
  operator--
  operator--(int)
                    adds or subtracts a number of months
  operator+=        \fI(public member function)\fP
  operator-=
                    retrieves the stored month value
  operator_unsigned \fI(public member function)\fP
                    checks if the stored month value is in the normal range
  ok                \fI(public member function)\fP


  Nonmember functions



  operator==
  operator!=  compares two month objects
  operator<   \fI(function)\fP
  operator<=
  operator>
  operator>=
              performs arithmetic on months
  operator+   \fI(function)\fP
  operator-
              outputs a month into a stream
  operator<<  \fI(function template)\fP
              outputs a month into a stream according to the provided format
  to_stream   \fI(function template)\fP
              parses a month from a stream according to the provided format
  from_stream \fI(function template)\fP




