.TH std::streamsize 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::streamsize \- std::streamsize

.SH Synopsis

  Defined in header <ios>
  typedef /*unspecified*/ streamsize;

  The type std::streamsize is a signed integral type used to represent the number of characters transferred in an I/O operation or the size of an I/O buffer. It is used as a signed counterpart of std::size_t, similar to the POSIX type ssize_t.
  Except in the constructors of std::strstreambuf, negative values of std::streamsize are never used.

.SH See also


         returns number of characters extracted by last unformatted input operation
  gcount \fI(public member function of std::basic_istream<CharT,Traits>)\fP
         extracts and discards characters until the given character is found
  ignore \fI(public member function of std::basic_istream<CharT,Traits>)\fP
         extracts blocks of characters
  read   \fI(public member function of std::basic_istream<CharT,Traits>)\fP
         inserts blocks of characters
  write  \fI(public member function of std::basic_ostream<CharT,Traits>)\fP




