.TH std::clearerr 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::clearerr \- std::clearerr

.SH Synopsis

Defined in header <cstdio>
void clearerr( std::FILE* stream );

Resets the error flags and the EOF indicator for the given file stream.

.SH Parameters


stream - the file to reset the error flags for


.SH Return value

\fI(none)\fP

.SH Example


 This section is incomplete
 Reason: no example


.SH See also


       checks for the end-of-file
feof   \fI(function)\fP
       displays a character string corresponding of the current error to stderr
perror \fI(function)\fP
       checks for a file error
ferror \fI(function)\fP




