.TH std::experimental::basic_string_view<CharT,Traits>::back 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::basic_string_view<CharT,Traits>::back \- std::experimental::basic_string_view<CharT,Traits>::back

.SH Synopsis

constexpr const_reference back() const;  (library fundamentals TS)

Returns reference to the last character in the view.

.SH Parameters

\fI(none)\fP

.SH Return value

Reference to the last character, equivalent to operator[](size() - 1).

.SH Complexity

Constant.

.SH See also


      accesses the first character
front \fI(public member function)\fP




