.TH std::unique_lock<Mutex>::unlock 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::unique_lock<Mutex>::unlock \- std::unique_lock<Mutex>::unlock

.SH Synopsis

void unlock();  \fI(since C++11)\fP

Unlocks the associated mutex and releases ownership.
std::system_error is thrown if there is no associated mutex or if the mutex is not locked.

.SH Parameters

\fI(none)\fP

.SH Return value

\fI(none)\fP

.SH Exceptions


* Any exceptions thrown by mutex()->unlock()


* If there is no associated mutex or the mutex is not locked, std::system_error with an error code of std::errc::operation_not_permitted


.SH Example


 This section is incomplete
 Reason: no example


.SH See also


        locks the associated mutex
lock    \fI(public member function)\fP
        disassociates the associated mutex without unlocking it
release \fI(public member function)\fP




