.TH std::mask_array<T>::~mask_array 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::mask_array<T>::~mask_array \- std::mask_array<T>::~mask_array

.SH Synopsis
   ~mask_array();

   Destroys the indexes in the array. The elements referred to by the object are not modified.
