.TH std::tuple_element<std::span> 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::tuple_element<std::span> \- std::tuple_element<std::span>

.SH Synopsis

  Defined in header <span>
  template< std::size_t I, class T, std::size_t N >  \fI(since C++20)\fP
  struct tuple_element<I, std::span<T, N> >;

  Provides compile-time indexed access to the type of the elements of the span using tuple-like interface. The program is ill-formed if I >= N or if N == std::dynamic_extent.

.SH Member types


  Member type Definition
  type        the type of elements of the span, i.e., T


.SH Example


   This section is incomplete
   Reason: no example


.SH See also


                                 obtains the type of the specified element
  tuple_element                  \fI(class template specialization)\fP

  std::tuple_element<std::pair>  obtains the type of the elements of pair
                                 \fI(class template specialization)\fP
  \fI(C++11)\fP
                                 obtains the type of the elements of array
  std::tuple_element<std::array> \fI(class template specialization)\fP




