.TH std::experimental::pmr::polymorphic_allocator<T>::select_on_container_copy_construction 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::pmr::polymorphic_allocator<T>::select_on_container_copy_construction \- std::experimental::pmr::polymorphic_allocator<T>::select_on_container_copy_construction

.SH Synopsis
   polymorphic_allocator select_on_container_copy_construction() const;  (library fundamentals TS)

   Returns a default-constructed polymorphic_allocator object.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A default-constructed polymorphic_allocator object.

.SH Notes

   polymorphic_allocators do not propagate on container copy construction.

.SH See also

   select_on_container_copy_construction obtains the allocator to use after copying a standard container
   \fB[static]\fP                              \fI(public static member function of std::allocator_traits<Alloc>)\fP
