.TH std::experimental::basic_string_view<CharT,Traits>::find_last_of 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::basic_string_view<CharT,Traits>::find_last_of \- std::experimental::basic_string_view<CharT,Traits>::find_last_of

.SH Synopsis

  constexpr size_type find_last_of(basic_string_view v, size_type pos = npos) const noexcept; \fB(1)\fP (library fundamentals TS)
  constexpr size_type find_last_of(CharT c, size_type pos = npos) const noexcept;             \fB(2)\fP (library fundamentals TS)
  constexpr size_type find_last_of(const CharT* s, size_type pos, size_type count) const;     \fB(3)\fP (library fundamentals TS)
  constexpr size_type find_last_of(const CharT* s, size_type pos = npos) const;               \fB(4)\fP (library fundamentals TS)

  Finds the last character equal to any of the characters in the given character sequence.
  1) Finds the last occurence of any of the characters of v in this view, starting at position pos.
  2) Equivalent to find_last_of(basic_string_view(&c, 1), pos).
  3) Equivalent to find_last_of(basic_string_view(s, count), pos).
  4) Equivalent to find_last_of(basic_string_view(s), pos).

.SH Parameters


  v     - view to search for
  pos   - position at which to start the search
  count - length of the string of characters to search for
  s     - pointer to a string of characters to search for
  ch    - character to search for


.SH Return value

  Position of the last occurrence of any character of the substring, or npos if no such character is found.

.SH Complexity

  O(size() * v.size()) at worst.

.SH See also


                    find characters in the view
  find              \fI(public member function)\fP
                    find the last occurrence of a substring
  rfind             \fI(public member function)\fP
                    find first occurrence of characters
  find_first_of     \fI(public member function)\fP
                    find first absence of characters
  find_first_not_of \fI(public member function)\fP
                    find last absence of characters
  find_last_not_of  \fI(public member function)\fP




