.TH std::chrono::weekday::operator+=,std::chrono::weekday::operator-= 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::weekday::operator+=,std::chrono::weekday::operator-= \- std::chrono::weekday::operator+=,std::chrono::weekday::operator-=

.SH Synopsis

  constexpr std::chrono::weekday& operator+=(const std::chrono::days& d) noexcept; \fB(1)\fP \fI(since C++20)\fP
  constexpr std::chrono::weekday& operator-=(const std::chrono::days& d) noexcept; \fB(2)\fP \fI(since C++20)\fP

  Adds or subtracts d.count() from the weekday value, reducing the result modulo 7 to an integer in the range [0, 6].
  1) Performs *this = *this + d;
  2) Performs *this = *this - d;

.SH Return value

  A reference to this weekday after modification.

.SH Notes

  After a call to one of these functions, ok() is always true if no overflow occurred during the operation.

.SH Example


   This section is incomplete
   Reason: no example


.SH See also



  operator++      increments or decrements the weekday
  operator++(int) \fI(public member function)\fP
  operator--
  operator--(int)
                  performs arithmetic on weekdays
  operator+       \fI(function)\fP
  operator-




