.TH std::experimental::source_location::column 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::experimental::source_location::column \- std::experimental::source_location::column

.SH Synopsis

constexpr std::uint_least32_t column() const noexcept;  (library fundamentals TS v2)

Returns an implementation-defined value representing some offset from the start of the line represented by this object (i.e., the column number).

.SH Parameters

\fI(none)\fP

.SH Return value

An implementation-defined value representing some offset from the start of the line represented by this object (i.e., the column number).

.SH Example


 This section is incomplete
 Reason: no example


.SH See also


              return the line number represented by this object
line          \fI(public member function)\fP
              return the file name represented by this object
file_name     \fI(public member function)\fP
              return the name of the function represented by this object, if any
function_name \fI(public member function)\fP




