.TH std::chrono::operator==,!=,<,<=,>,>=(std::chrono::link) 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::chrono::operator==,!=,<,<=,>,>=(std::chrono::link) \- std::chrono::operator==,!=,<,<=,>,>=(std::chrono::link)

.SH Synopsis

  bool operator==(const std::chrono::link& x, const std::chrono::link& y) noexcept; \fB(1)\fP \fI(since C++20)\fP
  bool operator!=(const std::chrono::link& x, const std::chrono::link& y) noexcept; \fB(2)\fP \fI(since C++20)\fP
  bool operator< (const std::chrono::link& x, const std::chrono::link& y) noexcept; \fB(3)\fP \fI(since C++20)\fP
  bool operator> (const std::chrono::link& x, const std::chrono::link& y) noexcept; \fB(4)\fP \fI(since C++20)\fP
  bool operator<=(const std::chrono::link& x, const std::chrono::link& y) noexcept; \fB(5)\fP \fI(since C++20)\fP
  bool operator>=(const std::chrono::link& x, const std::chrono::link& y) noexcept; \fB(6)\fP \fI(since C++20)\fP

  Compares the two link objects x and y by name.

.SH Return value

  1) x.name() == y.name().
  2) x.name() != y.name().
  3) x.name() < y.name().
  4) x.name() > y.name().
  5) x.name() <= y.name().
  6) x.name() >= y.name().



