.TH std::nested_exception::operator= 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::nested_exception::operator= \- std::nested_exception::operator=

.SH Synopsis

  nested_exception& operator=( const nested_exception& other ) noexcept = default;  \fI(since C++11)\fP

  Replaces the stored exception with the one held in other.

.SH Parameters


  other - nested exception to replace the contents with


.SH Return value

  *this



