.TH std::fputwc 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::fputwc \- std::fputwc

.SH Synopsis

Defined in header <cwchar>
wint_t fputwc( wchar_t ch, std::FILE* stream );
wint_t putwc( wchar_t ch, std::FILE* stream );

Writes a wide character ch to the given output stream stream. putwc() may be implemented as a macro and may evaluate stream more than once.

.SH Parameters


ch     - wide character to be written
stream - the output stream


.SH Return value

ch on success, WEOF on failure. If an encoding error occurs, errno is set to EILSEQ.

.SH See also


       writes a character to a file stream
fputc  \fI(function)\fP
putc
       writes a wide string to a file stream
fputws \fI(function)\fP
       gets a wide character from a file stream
fgetwc \fI(function)\fP
getwc




